[package]
authors = ["Michael Gattozzi <mgattozzi@gmail.com>"]
description = "Pure Rust bindings to the Github API"
name = "github-rs"
version = "0.2.0"
license = "MIT"
repository = "https://github.com/mgattozzi/github-rs.git"
homepage = "https://github.com/mgattozzi/github-rs"
documentation = "https://mgattozzi.github.io/github-rs"

[dependencies]
hyper = "0.9.10"
serde = "^0.8.0"
serde_json = "^0.8.0"
serde_derive = "^0.8.0"
solicit = "0.4.4"
url = "1.1.1"

[dependencies.clippy]
optional = true
version = "0.0.104"

[features]
default = []
dev = ["clippy"]
