[package]
authors = ["Michael Gattozzi <mgattozzi@gmail.com>"]
description = "Pure Rust bindings to the Github API"
name = "github-rs"
version = "0.4.1"
license = "MIT"
repository = "https://github.com/mgattozzi/github-rs.git"
homepage = "https://github.com/mgattozzi/github-rs"
documentation = "https://mgattozzi.github.io/github-rs"

[dependencies]
hyper = "0.10"
hyper-rustls= "0.3"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
url = "1.2"

[dependencies.clippy]
optional = true
version = "0.0.104"

[features]
default = []
dev = ["clippy"]
